spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties.hibernate.format_sql: true

  datasource:
    url: jdbc:h2:mem:hrms
    username: sa
    password: sa
    initialize: false

  resources:
    add-mappings: false

# Enabling H2 Console
spring.h2.console.enabled: true

# exception handling
server.error.whitelabel.enabled: false
spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false

